repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
  - repo: https://github.com/python/black
    rev: 21.5b1
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        language_version: python3.9
        additional_dependencies:
          - flake8-bugbear
          - pep8-naming

default_language_version:
  python: python3

exclude: /migrations/
