# Generated by Django 3.2.6 on 2021-12-10 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('username', models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(db_index=True, max_length=250, null=True, verbose_name='이메일')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=32, region=None, verbose_name='전화번호')),
                ('name', models.CharField(max_length=10, null=True, verbose_name='이름')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_admin', models.BooleanField(default=False, verbose_name='어드민')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 목록',
                'db_table': 'member_user',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('introduce', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='소개')),
                ('extra', models.JSONField(blank=True, default=dict, null=True, verbose_name='추가 정보')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='member.user', verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 프로필',
                'verbose_name_plural': '회원 프로필 목록',
                'db_table': 'member_user_profile',
            },
        ),
        migrations.CreateModel(
            name='UserPasscodeVerify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('requester_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=32, region=None, verbose_name='요청자 전화번호')),
                ('requsster_device_uuid', models.CharField(max_length=100, verbose_name='요청자 디바이스 UUID')),
                ('passcode', models.CharField(max_length=6, verbose_name='패스코드')),
                ('status', models.CharField(choices=[('used', '완료된 검증'), ('pending', '검증 대기중'), ('expire', '만료 됨')], default='pending', max_length=20, verbose_name='인증 상태')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sms_set', to='member.user', verbose_name='인증되는 회원')),
            ],
            options={
                'verbose_name': '회원 패스코드 인증 요청',
                'verbose_name_plural': '회원 패스코드 인증 요청',
                'db_table': 'member_user_passcode_verify',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted', 'is_active'], name='member_user_deleted_d70448_idx'),
        ),
    ]
