# Generated by Django 3.2.6 on 2021-12-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_registration',
            field=models.BooleanField(default=False, verbose_name='등록 여부'),
        ),
    ]
