# Generated by Django 3.2.6 on 2021-12-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_user_is_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_registration',
            field=models.BooleanField(default=False, verbose_name='등록 완료 여부'),
        ),
    ]
