# Generated by Django 3.2.6 on 2021-12-11 01:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_user_is_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpasscodeverify',
            old_name='requsster_device_uuid',
            new_name='requester_device_uuid',
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='토큰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='member.user', verbose_name='회원')),
            ],
            options={
                'verbose_name': '회원 토큰',
                'verbose_name_plural': '회원 토큰 목록',
                'db_table': 'member_user_token',
            },
        ),
    ]
