# Generated by Django 3.2.6 on 2021-12-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20211211_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasscodeverify',
            name='user',
        ),
        migrations.AddField(
            model_name='userpasscodeverify',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='auth_sms_set', to='member.User', verbose_name='인증되는 회원'),
        ),
    ]
