# Generated by Django 3.2.6 on 2021-12-11 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20211211_0215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpasscodeverify',
            name='user',
        ),
        migrations.AddField(
            model_name='userpasscodeverify',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auth_sms_set', to='member.user', verbose_name='인증되는 회원'),
        ),
    ]
