# Generated by Django 3.2.6 on 2021-12-11 03:01

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20211211_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='policy_for_privacy_agreed',
            field=model_utils.fields.AutoCreatedField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='개인정보 취급방침 동의일'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='policy_for_terms_agreed',
            field=model_utils.fields.AutoCreatedField(blank=True, default=django.utils.timezone.now, editable=False, null=True, verbose_name='이용약관 동의일'),
        ),
    ]
