# Generated by Django 3.2.6 on 2021-12-11 04:27

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20211211_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=32, region=None, unique=True, verbose_name='전화번호'),
        ),
    ]
