# Generated by Django 3.2.6 on 2021-12-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpasscodeverify',
            name='expire_at',
            field=models.DateTimeField(null=True, verbose_name='만료 시간'),
        ),
    ]
