# Generated by Django 3.2.6 on 2021-12-12 02:54

import apps.member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_userpasscodeverify_expire_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=apps.member.storages.profile_image_upload),
        ),
    ]
