# Generated by Django 3.2.6 on 2021-12-13 15:08

import apps.member.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=apps.member.storages.profile_image_upload, verbose_name='프로필 이미지 파일'),
        ),
    ]
