# Generated by Django 3.2.6 on 2021-12-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0013_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생일'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', '남자'), ('FEMALE', '여자')], max_length=20, null=True, verbose_name='성별'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='주소'),
        ),
    ]
