# Generated by Django 3.2.6 on 2021-12-13 16:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0014_auto_20211213_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSNS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='SNS')),
                ('url', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='URL')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sns_set', to='member.userprofile', verbose_name='회원 프로필')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
