# Generated by Django 3.2.6 on 2021-12-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0015_usersns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersns',
            old_name='name',
            new_name='username',
        ),
    ]
