# Generated by Django 3.2.6 on 2021-12-13 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0016_rename_name_usersns_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersns',
            options={'verbose_name': '회원 SNS', 'verbose_name_plural': '회원 SNS 목록'},
        ),
        migrations.AlterModelTable(
            name='usersns',
            table='member_user_profile_sns',
        ),
    ]
