# Generated by Django 3.2.6 on 2021-12-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0017_auto_20211213_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersns',
            name='token',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='토큰'),
        ),
    ]
