# Generated by Django 3.2.6 on 2022-01-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0018_usersns_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='type',
            field=models.CharField(choices=[('refresh', 'REFRESH'), ('access', 'ACCESS')], default='access', max_length=20, verbose_name='토큰 형태'),
        ),
    ]
