# Generated by Django 3.2.6 on 2022-01-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0020_auto_20220129_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersocialtoken',
            name='expire_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
