# Generated by Django 3.2.6 on 2022-01-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0021_usersocialtoken_expire_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersocial',
            options={'verbose_name': '회원 소셜 계정', 'verbose_name_plural': '회원 소셜 계정 목록'},
        ),
        migrations.RemoveField(
            model_name='usersocial',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='usersocial',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='social_set', to='member.user', verbose_name='회원'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersocialtoken',
            name='social',
            field=models.CharField(choices=[('used', '유효함'), ('expire', '만료됨')], default=0, max_length=20, verbose_name='소셜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='user_key',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True, verbose_name='소셜 계정 식별키'),
        ),
    ]
