# Generated by Django 3.2.6 on 2022-01-29 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0022_auto_20220129_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersocial',
            old_name='user_key',
            new_name='social_key',
        ),
        migrations.RemoveField(
            model_name='usersocial',
            name='token',
        ),
        migrations.AlterField(
            model_name='usersocialtoken',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_set', to='member.usersocial', verbose_name='소셜 계정'),
        ),
    ]
