# Generated by Django 3.2.6 on 2021-12-05 05:40

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('shop_name', models.CharField(max_length=128, verbose_name='지점명')),
                ('manager_name', models.CharField(max_length=32, verbose_name='담장자 이름')),
                ('manager_phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=32, region=None, verbose_name='담장자 전화번호')),
                ('expired_datetime', models.DateField(verbose_name='마감일')),
                ('working_hour_start', models.IntegerField(verbose_name='업무 시작시간')),
                ('working_hour_end', models.IntegerField(verbose_name='업무 종료시간')),
                ('pay_type', models.CharField(choices=[('HO', '시급'), ('DA', '일급'), ('WE', '주급'), ('MO', '월급'), ('YE', '연봉'), ('IR', '무관')], max_length=2, verbose_name='급여 종류')),
                ('pay_amount', models.IntegerField(verbose_name='급여량')),
                ('description', models.TextField(blank=True, null=True, verbose_name='상세내용')),
                ('employee_types', models.ManyToManyField(related_name='announcements', to='announcement.EmployeeType')),
            ],
        ),
    ]
