# Generated by Django 3.2.6 on 2021-12-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='expired_datetime',
            field=models.DateTimeField(verbose_name='마감일'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='pay_amount',
            field=models.PositiveIntegerField(verbose_name='급여량'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='working_hour_end',
            field=models.DateTimeField(verbose_name='업무 종료시간'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='working_hour_start',
            field=models.DateTimeField(verbose_name='업무 시작시간'),
        ),
    ]
