# Generated by Django 3.2.6 on 2021-12-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_auto_20211210_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='external_id',
            field=models.IntegerField(null=True, verbose_name='외부 ID'),
        ),
    ]
