# Generated by Django 3.2.6 on 2022-01-09 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0004_employeetype_codename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='working_hour_end',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='working_hour_start',
        ),
        migrations.AddField(
            model_name='announcement',
            name='working_hour',
            field=models.CharField(default='', max_length=128, verbose_name='업무시간'),
            preserve_default=False,
        ),
    ]
