# Generated by Django 3.2.6 on 2022-01-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0005_auto_20220109_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='external_id',
            field=models.IntegerField(db_index=True, null=True, verbose_name='외부 ID'),
        ),
    ]
