# Generated by Django 3.2.6 on 2022-01-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0007_announcement_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expire_type',
            field=models.CharField(choices=[('AL', '상시모집'), ('BA', '기본'), ('FI', '충원시 마감')], default='BA', max_length=2, verbose_name='마감 타입'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='announcement',
            name='expired_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='마감일'),
        ),
    ]
