# Generated by Django 3.2.6 on 2022-02-12 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('announcement', '0009_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='address.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='address.country'),
        ),
    ]
