# Generated by Django 3.2.6 on 2022-02-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0010_auto_20220212_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(null=True, verbose_name='이미지 URL'),
        ),
    ]
