USER = 'USER'
USER_SNS = 'USER.SNS'

RESUME = 'RESUME'
RESUME_CAREER = 'RESUME.CAREER'
RESUME_CERTIFICATE = 'RESUME.CERTIFICATE'
RESUME_ACADEMIC = 'RESUME.ACADEMIC'
RESUME_MILITARY = 'RESUME.MILITARY'

PASSCODE = 'PASSCODE'
AUTH = 'AUTH'
