# Generated by Django 3.2.6 on 2021-12-13 15:09

import apps.resume.storages
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='이력서 이름')),
                ('pdf', models.FileField(upload_to=apps.resume.storages.resume_pdf_upload, verbose_name='이력서 파일')),
                ('extra', models.JSONField(blank=True, default=dict, null=True, verbose_name='추가 정보')),
            ],
            options={
                'verbose_name': '이력서',
                'verbose_name_plural': '이력서 목록',
                'db_table': 'resume_resume',
            },
        ),
    ]
