# Generated by Django 3.2.6 on 2021-12-13 23:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20211213_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilitaryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('service', models.CharField(blank=True, choices=[('NA', '해당없음'), ('EXEMPTION', '면제'), ('UNFINISHED', '미필'), ('FINISHED', '군필')], max_length=20, null=True, verbose_name='병역')),
                ('exemption_reason', models.CharField(blank=True, choices=[('NA', '해당없음'), ('EXEMPTION', '면제'), ('UNFINISHED', '미필'), ('FINISHED', '군필')], max_length=250, null=True, verbose_name='면제사유')),
                ('join_at', models.DateTimeField(verbose_name='입사일')),
                ('quit_at', models.DateTimeField(verbose_name='퇴사일')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military', to='resume.resume', verbose_name='회원')),
            ],
            options={
                'verbose_name': '이력서',
                'db_table': 'member_user_resume_military',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='이름')),
                ('vendor', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='발급기관')),
                ('certificate_at', models.DateTimeField(verbose_name='취득일')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='resume.resume', verbose_name='회원')),
            ],
            options={
                'verbose_name': '이력서',
                'db_table': 'member_user_resume_certificate',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('company', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='회사')),
                ('position', models.CharField(blank=True, choices=[('STAFF', '스탭(인턴)'), ('MANAGER', '매니저'), ('DESIGNER', '디자이너'), ('DIRECTOR', '원장')], max_length=20, null=True, verbose_name='직급')),
                ('join_at', models.DateTimeField(verbose_name='입사일')),
                ('quit_at', models.DateTimeField(null=True, verbose_name='퇴사일')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='resume.resume', verbose_name='회원')),
            ],
            options={
                'verbose_name': '이력서',
                'db_table': 'member_user_resume_career',
            },
        ),
        migrations.CreateModel(
            name='AcademicBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='학교명')),
                ('department', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='학과명')),
                ('location', models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='소재지')),
                ('join_at', models.DateTimeField(verbose_name='입사일')),
                ('quit_at', models.DateTimeField(null=True, verbose_name='퇴사일')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic', to='resume.resume', verbose_name='회원')),
            ],
            options={
                'verbose_name': '이력서',
                'db_table': 'member_user_resume_academic',
            },
        ),
    ]
