# Generated by Django 3.2.6 on 2021-12-13 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_academicbackground_career_certificate_militaryservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryservice',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military', to='resume.resume', verbose_name='회원'),
        ),
    ]
