# Generated by Django 3.2.6 on 2021-12-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_militaryservice_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryservice',
            name='exemption_reason',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='면제사유'),
        ),
    ]
