# Generated by Django 3.2.6 on 2021-12-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_alter_militaryservice_exemption_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academicbackground',
            old_name='department',
            new_name='major',
        ),
        migrations.AddField(
            model_name='career',
            name='worked_on',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='업무 내용'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='vendor',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='발급 기관'),
        ),
    ]
