# Generated by Django 3.2.6 on 2022-01-09 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20211214_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_set', to='resume.resume', verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='career',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_set', to='resume.resume', verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_set', to='resume.resume', verbose_name='회원'),
        ),
        migrations.AlterField(
            model_name='militaryservice',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military_set', to='resume.resume', verbose_name='회원'),
        ),
    ]
