# Generated by Django 3.2.6 on 2022-01-09 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20220109_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='militaryservice',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='military', to='resume.resume', verbose_name='회원'),
        ),
    ]
