# Generated by Django 3.2.6 on 2022-01-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_militaryservice_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='join_at',
            field=models.DateTimeField(blank=True, verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='militaryservice',
            name='join_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='입대일'),
        ),
        migrations.AlterField(
            model_name='militaryservice',
            name='quit_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='전역일'),
        ),
    ]
