# Generated by Django 3.2.6 on 2022-01-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20220109_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicbackground',
            name='join_at',
            field=models.DateField(blank=True, verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='academicbackground',
            name='quit_at',
            field=models.DateField(null=True, verbose_name='퇴사일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='join_at',
            field=models.DateField(verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='career',
            name='quit_at',
            field=models.DateField(null=True, verbose_name='퇴사일'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_at',
            field=models.DateField(verbose_name='취득일'),
        ),
        migrations.AlterField(
            model_name='militaryservice',
            name='join_at',
            field=models.DateField(blank=True, null=True, verbose_name='입대일'),
        ),
        migrations.AlterField(
            model_name='militaryservice',
            name='quit_at',
            field=models.DateField(blank=True, null=True, verbose_name='전역일'),
        ),
    ]
