# Generated by Django 3.2.6 on 2022-01-17 15:43

import apps.resume.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_auto_20220111_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(null=True, upload_to=apps.resume.storages.resume_pdf_upload, verbose_name='프로필 이미지 파일'),
        ),
    ]
