# Generated by Django 3.2.6 on 2021-10-15 03:17

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('deleted', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('username', models.CharField(db_index=True, max_length=200, null=True, unique=True, verbose_name='아이디')),
                ('email', models.EmailField(db_index=True, max_length=250, null=True, verbose_name='이메일')),
                ('nickname', models.CharField(db_index=True, max_length=20, null=True, unique=True, verbose_name='닉네임')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('is_admin', models.BooleanField(default=False, verbose_name='어드민')),
            ],
            options={
                'verbose_name': '회원',
                'verbose_name_plural': '회원 목록',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted', 'is_active'], name='user_user_deleted_23ecc2_idx'),
        ),
    ]
